In [194]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

**DEFINIZIOE DATASET**

In [195]:
train = pd.read_csv("/kaggle/input/titanic/train.csv")
test = pd.read_csv("/kaggle/input/titanic/test.csv")

**PULIZIA DEI DATI NAN DEL DATASET**

In [196]:
valNulliTrain = train.isnull().sum()
print(valNulliTrain )
mediana = train["Age"].median()
print(f"il valore della mediana è {mediana}")
train["Age"] = train["Age"].fillna(mediana)
valNulliAgg = train.isnull().sum()
print(valNulliAgg)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
il valore della mediana è 28.0
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [197]:
valNulliTest = test.isnull().sum()
print(valNulliTest)
mediana = test["Age"].median()
print(f"il valore della mediana è {mediana}")
test["Age"] = test["Age"].fillna(mediana)
valNulliAgg = test.isnull().sum()
print(valNulliAgg)

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64
il valore della mediana è 27.0
PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

**CONVERSIONE DEI DATI CATEGORICI IN NUMERICI**

In [ ]:
train["Sex"] = train["Sex"].replace({"male": 1, "female": 0})
test["Sex"] = test["Sex"].replace({"male": 1, "female": 0})
print(train)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1
2                               Heikkinen, Miss. Laina    0  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1
4                             Allen, Mr. William Henry    1  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    1  27.0      0
887                       Graham, Miss. Margaret Edith    0  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    0  28.0      1
889                              Behr, Mr. Karl Howell    1  26.0      0
890                                Dooley, Mr. Patrick    1  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1
2                               Heikkinen, Miss. Laina    0  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1
4                             Allen, Mr. William Henry    1  35.0      0
..                                                 ...  ...   ...    ...
886                              Montvila, Rev. Juozas    1  27.0      0
887                       Graham, Miss. Margaret Edith    0  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"    0  28.0      1
889                              Behr, Mr. Karl Howell    1  26.0      0
890                                Dooley, Mr. Patrick    1  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

**GRAFICO DISTRIBUZIONI DELL'ETA'**

In [ ]:
import matplotlib.pyplot as plt

eta = train["Age"]

plt.figure(figsize=(20,10))
plt.hist(eta)
plt.title("distribuzione dell'eta'")
plt.show()

**GRAFICO DISTRIBUZIONE SESSO**

In [ ]:
import matplotlib.pyplot as plt

sesso = train["Sex"]

plt.figure(figsize=(20,10))
plt.hist(sesso)
plt.title("distribuzione del sesso delle persone")
plt.show()

**GRAFICO DISTRIBUZIONE CLASSI**

In [ ]:
import matplotlib.pyplot as plt

classi = train["Pclass"]

plt.figure(figsize=(20,10))
plt.hist(classi)
plt.title("distribuzione delle eprsone in funzione delle classi'")
plt.show()

**GRAFICI CORRELAZIONI PARAMETRI**

In [ ]:
import matplotlib.pyplot as plt

x = train["Age"]
y = train["Survived"]
colors=[]
for i in range(len(train["Age"])):
    colors.append(i)

plt.figure(figsize=(20,10))
plt.scatter(x,y, marker="o", c=colors, cmap="viridis")
plt.title("correlazione tra età e sopravvissuti")
plt.xlabel("eta")
plt.ylabel("sopravvissuti")
plt.colorbar()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = train["Sex"]
y = train["Survived"]
colors=[]
for i in range(len(train["Sex"])):
    colors.append(i)

plt.figure(figsize=(20,10))
plt.scatter(x,y, marker="o", c=colors, cmap="viridis")
plt.title("correlazione tra sesso e sopravvissuti")
plt.xlabel("sesso")
plt.ylabel("sopravvissuti")
plt.colorbar()
plt.show()

In [ ]:
import matplotlib.pyplot as plt

x = train["Pclass"]
y = train["Survived"]
colors=[]
for i in range(len(train["Pclass"])):
    colors.append(i)

plt.figure(figsize=(20,10))
plt.scatter(x,y, marker="o", c=colors, cmap="viridis")
plt.title("correlazione tra classe e sopravvissuti")
plt.xlabel("classe")
plt.ylabel("sopravvissuti")
plt.colorbar()
plt.show()

In [ ]:
X_train = train[["Pclass","Sex", "Age"]]
y_train= train["Survived"]

X_test = test[["Pclass","Sex", "Age"]]

**ALLENAMENTO DEL MODELLO**

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

**PREDIZIONI MODELLO**

In [ ]:
y_pred = model.predict(X_test)

**CONVERSIONE PROBABILITA' PREDETTE IN VALORI BINARI**

In [ ]:
y_pred_binary = (y_pred > 0.5).astype(int)

**CREAZIONE DATASET SUBMISSION**

In [ ]:
predictions = pd.DataFrame({
    "PassengerId": test["PassengerId"],  
    "Survived":y_pred_binary
})

predictions.to_csv("predictions.csv", index=False)  
print(predictions)